name: Build and deploy ASP.NET Core app to Azure Web App - RushikeshAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages
        run: dotnet restore ./WebApplication2/WebApplication2/WebApplication2.csproj

      - name: Build
        run: dotnet build ./WebApplication2/WebApplication2/WebApplication2.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./WebApplication2/WebApplication2/WebApplication2.csproj --configuration Release --no-build --output "${{ github.workspace }}/publish"

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9419BBDE98D64E949F20FBB90E29CDA8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_457ED58A06C54FFF96DF28A1D5214DCC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0CCE7AB73AC24AF4A732A571186F1C41 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: RushikeshAPI
          slot-name: Production
          package: publish
